class ModuleDescription {

  static Map allBibleMap = {
    "ABG": "Apostolic Bible Greek Text",
    "ASV": "American Standard Version",
    "BBE": "Bible in Basic English",
    "BSB": "Berean Study Bible",
    "CCB": "當代聖經修訂版〔繁體〕",
    "CCBs": "当代圣经修订版〔简体〕",
    "CEB": "Common English Bible",
    "CEV": "Contemporary English Version",
    "CSB": "Christian Standard Bible",
    "CUV": "中文和合本〔繁體〕",
    "CUVs": "中文和合本〔简体〕",
    "ERV": "English Revised Version",
    "ESV": "English Standard Version",
    "EXP": "The Expanded Bible",
    "ISV": "International Standard Version",
    "KJV": "King James Version",
    "LEB": "Lexham English Bible",
    "LXX1": "Septuagint [Rahlfs 1935]; main text",
    "LXX1i": "Septuagint [Rahlfs 1935]; main text [interlinear]",
    "LXX2": "Septuagint [Rahlfs 1935]; alternate text",
    "LXX2i": "Septuagint [Rahlfs 1935]; alternate text [interlinear]",
    "LXXE": "Brenton English Septuagint",
    "LXXGNT": "Septuagint & Greek New Testament",
    "LXXGNTi": "Septuagint & Greek New Testament [interlinear]",
    "LXXk": "Septuagint [KJV versification]",
    "MSG": "The Message",
    "NASB": "New American Standard Bible",
    "NET": "New English Translation",
    "NIV": "New International Version",
    "NKJV": "New King James Version",
    "NLT": "New Living Translation",
    "NRSV": "New Revised Standard Version",
    "OHGB": "Open Hebrew & Greek Bible",
    "OHGBi": "Open Hebrew & Greek Bible [interlinear]",
    "OHGBt": "Open Hebrew & Greek Bible [transliteration]",
    "T4T": "Translation for Translators",
    "ULT": "UnfoldingWord Literal Text",
    "UST": "UnfoldingWord Simplified Text",
    "WEB": "World English Bible",
    "AMP": "Amplified Bible",
    "AMPC": "Amplified Bible, Classic Edition",
    "NA28": "NA28 Greek New Testament",
    "NETS": "New English Translation of the Septuagint",
    "NETS2": "New English Translation of the Septuagint [alternate texts]",
    "NJPS": "New Jewish Publication Society of America Tanakh",
    "TNK": "Tanakh",
    "UBS5": "UBS5 Greek New Testament",
  };

  static List<String> hebrewBibles = ["OHGB", "OHGBi"];
  static List<String> greekBibles = [
    "ABG",
    "LXX1",
    "LXX2",
    "LXXk",
    "OHGB",
    "OHGBi",
    "LXXGNT",
    "LXXGNTi",
    "LXX1i",
    "LXX2i",
    "NA28",
    "UBS5"
  ];
  static List<String> interlinearBibles = ["OHGBi", "LXXGNTi", "LXX1i", "LXX2i"];
  static List<String> chineseBibles = ["CCB", "CCBs", "CUV", "CUVs"];

  // public versions
/*
  static List<String> allBibleList = [
    "ABG",
    "ASV",
    "BBE",
    "BSB",
    "CUV",
    "CUVs",
    "ERV",
    "ISV",
    "KJV",
    "LEB",
    "LXX1",
    "LXX1i",
    "LXX2",
    "LXX2i",
    "LXXE",
    "LXXGNT",
    "LXXGNTi",
    "LXXk",
    "NET",
    "OHGB",
    "OHGBi",
    "OHGBt",
    "T4T",
    "ULT",
    "UST",
    "WEB"
  ];
*/
  // private versions

  static List<String> allBibleList = [
    "ABG",
    "AMP",
    "AMPC",
    "ASV",
    "BBE",
    "BSB",
    "CCB",
    "CCBs",
    "CEB",
    "CEV",
    "CSB",
    "CUV",
    "CUVs",
    "ERV",
    "ESV",
    "EXP",
    "ISV",
    "KJV",
    "LEB",
    "LXX1",
    "LXX1i",
    "LXX2",
    "LXX2i",
    "LXXE",
    "LXXGNT",
    "LXXGNTi",
    "LXXk",
    "MSG",
    "NA28",
    "NASB",
    "NET",
    "NETS",
    "NETS2",
    "NIV",
    "NJPS",
    "NKJV",
    "NLT",
    "NRSV",
    "OHGB",
    "OHGBi",
    "OHGBt",
    "T4T",
    "TNK",
    "UBS5",
    "ULT",
    "UST",
    "WEB"
  ];

  // variables linked with shared preferences

  // public versions
/*
  static List<String> compareBibleList = [
    "ASV",
    "BSB",
    "ERV",
    "ISV",
    "KJV",
    "LEB",
    "LXXk",
    "NET",
    "OHGB",
    "WEB",
  ];*/

  // private versions

  static List<String> compareBibleList = [
    "CEV",
    "CSB",
    "CUV",
    "ESV",
    "EXP",
    "ISV",
    "KJV",
    "LXXE",
    "LXXk",
    "NASB",
    "NET",
    "NIV",
    "OHGB"
  ];

  static Map<String, String> marvelCommentaries = {
    "Barnes": "Notes on the Old and New Testaments (Barnes) [26 vol.]",
    "Benson": "Commentary on the Old and New Testaments (Benson) [5 vol.]",
    "BI": "Biblical Illustrator (Exell) [58 vol.]",
    "Brooks": "Complete Summary of the Bible (Brooks) [2 vol.]",
    "Calvin": "John Calvin's Commentaries (Calvin) [22 vol.]",
    "Clarke": "Commentary on the Bible (Clarke) [6 vol.]",
    "CBSC": "Cambridge Bible for Schools and Colleges (Cambridge) [57 vol.]",
    "CECNT": "Critical And Exegetical Commentary on the NT (Meyer) [20 vol.]",
    "CGrk": "Cambridge Greek Testament for Schools and Colleges (Cambridge) [21 vol.]",
    "CHP": "Church Pulpit Commentary (Nisbet) [12 vol.]",
    "CPBST": "College Press Bible Study Textbook Series (College) [59 vol.]",
    "EBC": "Expositor's Bible Commentary (Nicoll) [49 vol.]",
    "ECER": "Commentary for English Readers (Ellicott) [8 vol.]",
    "EGNT": "Expositor's Greek New Testament (Nicoll) [5 vol.]",
    "GCT": "Greek Testament Commentary (Alford) [4 vol.]",
    "Gill": "Exposition of the Entire Bible (Gill) [9 vol.]",
    "Henry": "Exposition of the Old and New Testaments (Henry) [6 vol.]",
    "HH": "Horæ Homileticæ (Simeon) [21 vol.]",
    "ICCNT": "International Critical Commentary, NT (1896-1929) [16 vol.]",
    "JFB": "Jamieson, Fausset, and Brown Commentary (JFB) [6 vol.]",
    "KD": "Commentary on the Old Testament (Keil & Delitzsch) [10 vol.]",
    "Lange": "Commentary on the Holy Scriptures: Critical, Doctrinal, and Homiletical (Lange) [25 vol.]",
    "MacL": "Expositions of Holy Scripture (MacLaren) [32 vol.]",
    "PHC": "Preacher's Complete Homiletical Commentary (Exell) [37 vol.]",
    "Pulpit": "Pulpit Commentary (Spence) [23 vol.]",
    "Rob": "Word Pictures in the New Testament (Robertson) [6 vol.]",
    "Spur": "Spurgeon's Expositions on the Bible (Spurgeon) [3 vol.]",
    "Vincent": "Word Studies in the New Testament (Vincent) [4 vol.]",
    "Wesley": "John Wesley's Notes on the Whole Bible (Wesley) [3 vol.]",
    "Whedon": "Commentary on the Old and New Testaments (Whedon) [14 vol.]",
  };

}