name: unique_bible_app_hybrid
description: Unique Bible App Hybrid

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  scrollable_positioned_list: ^0.1.8
  shared_preferences: ^0.5.12+4
  flutter_launcher_icons: ^0.8.1
  sqflite: ^1.3.2+1
  share: ^0.6.5+4
  swipedetector: ^1.2.0
  photo_view: ^0.10.3
  url_launcher: ^5.7.10
  flutter_tts: ^2.1.0
  #large_file_copy: ^0.0.1
  chunked_stream: ^1.2.0
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  connectivity: ^2.0.2
  lpinyin: ^1.1.0
  lemmatizer: ^0.0.1
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1+1
  flutter_html: ^1.1.1
  webview_flutter: ^1.0.7
  flutter_parsed_text: ^1.2.5
  pie_chart: ^4.0.1
  fl_chart: ^0.12.2
  charts_flutter: ^0.9.0
  flutter_colorpicker: ^0.3.5

# Run the following command:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppIcon.png"
  adaptive_icon_foreground: "assets/images/AppIcon_foreground.png"
  adaptive_icon_background: "assets/images/AppIcon_background.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - assets/bibles/
    - assets/images/
    - assets/morphology/
    - assets/subheadings/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Ezra SIL
      fonts:
        - asset: assets/fonts/sileot.ttf
    - family: KoineGreek
      fonts:
        - asset: assets/fonts/KoineGreek.ttf
